import enum


class TripTag(str, enum.Enum):
    TREK = "TREK"
    BACKPACKING = "BACKPACKING"
    STARGAZING = "STARGAZING"
    RELAXING = "RELAXING"
    ADVENTURE = "ADVENTURE"
    SOLO = "SOLO"
    GROUP = "GROUP"
    WOMEN_ONLY = "WOMEN_ONLY"
    WOMEN_FRIENDLY = "WOMEN_FRIENDLY"
    BEGINNER_FRIENDLY = "BEGINNER_FRIENDLY"
    WEEKEND = "WEEKEND"
    MULTI_DAY = "MULTI_DAY"
    HIGH_ALTITUDE = "HIGH_ALTITUDE"
    CULTURAL_EXPERIENCE = "CULTURAL_EXPERIENCE"
    NATURE_RETREAT = "NATURE_RETREAT"
    PHOTOGRAPHY = "PHOTOGRAPHY"
    INSTAGRAMMABLE = "INSTAGRAMMABLE"
    BUDGET = "BUDGET"
    MID_RANGE = "MID_RANGE"
    PREMIUM = "PREMIUM"

