"""add organizers and enhance trips

Revision ID: 6c0582606bff
Revises: 8070408ca563
Create Date: 2026-01-03 13:31:34.582596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0582606bff'
down_revision: Union[str, Sequence[str], None] = '8070408ca563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create organizers table
    op.create_table(
        "organizers",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False, unique=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Add organizer_id as nullable
    op.add_column(
        "trips",
        sa.Column("organizer_id", sa.String(), nullable=True),
    )

    # Create default organizer
    op.execute("""
        INSERT INTO organizers (id, name, email)
        VALUES ('default-organizer', 'Default Organizer', 'default@system.local')
        ON CONFLICT DO NOTHING
    """)

    # Backfill trips
    op.execute("""
        UPDATE trips
        SET organizer_id = 'default-organizer'
        WHERE organizer_id IS NULL
    """)

    # Enforce NOT NULL
    op.alter_column("trips", "organizer_id", nullable=False)

    # Foreign key + uniqueness
    op.create_foreign_key(
        "fk_trips_organizer",
        "trips",
        "organizers",
        ["organizer_id"],
        ["id"],
    )

    op.create_unique_constraint(
        "uq_trip_no_duplicates",
        "trips",
        ["organizer_id", "title", "start_date"],
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint('uq_trip_slug', 'trips', type_='unique')
    op.drop_constraint('uq_trip_no_duplicates', 'trips', type_='unique')
    op.drop_column('trips', 'deleted_at')
    op.drop_column('trips', 'created_at')
    op.drop_column('trips', 'is_active')
    op.drop_column('trips', 'slug')
    op.drop_column('trips', 'organizer_id')
    op.drop_table('organizers')
    # ### end Alembic commands ###
