"""add total_seats to trips

Revision ID: 9048e106dd9a
Revises: 9641186d5e7b
Create Date: 2026-01-03 20:57:23.823127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9048e106dd9a'
down_revision: Union[str, Sequence[str], None] = '9641186d5e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trips', sa.Column('total_seats', sa.Integer(), nullable=True))
    op.execute("""
        UPDATE trips
        SET total_seats = 20
        WHERE total_seats IS NULL
    """)

    # Enforce NOT NULL
    op.alter_column("trips", "total_seats", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'total_seats')
    op.drop_table('bookings')
    # ### end Alembic commands ###
