"""add slug to trips

Revision ID: 9641186d5e7b
Revises: 6c0582606bff
Create Date: 2026-01-03 17:13:33.234787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9641186d5e7b'
down_revision: Union[str, Sequence[str], None] = '6c0582606bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('trips', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('trips', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('trips', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_trip_slug', 'trips', ['organizer_id', 'slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_trip_slug', 'trips', type_='unique')
    op.drop_column('trips', 'deleted_at')
    op.drop_column('trips', 'created_at')
    op.drop_column('trips', 'is_active')
    op.drop_column('trips', 'slug')
    # ### end Alembic commands ###